-- 코드를 작성해주세요
WITH RECURSIVE G AS(
    SELECT
        ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT
        E.ID,
        G.GENERATION+1
    FROM ECOLI_DATA E
    JOIN G ON E.PARENT_ID=G.ID
    )
    SELECT
        COUNT(*) AS COUNT,
        G.GENERATION
    FROM G
    LEFT JOIN ECOLI_DATA C
        ON C.PARENT_ID=G.ID
    WHERE C.ID IS NULL
    GROUP BY G.GENERATION
    ORDER BY G.GENERATION;
