-- 다음주면 맥뷱ㅇㄹ.....
SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
  ON I.ITEM_ID = T.ITEM_ID
LEFT JOIN ITEM_TREE C
  ON C.PARENT_ITEM_ID = I.ITEM_ID
WHERE C.ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;
