-- 컴퓨터고장 이슈로 태블릿으로 작업중입니닷.
SELECT
  B.CATEGORY AS CATEGORY,
  SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S
  ON S.BOOK_ID = B.BOOK_ID
WHERE S.SALES_DATE >= '2022-01-01'
  AND S.SALES_DATE <  '2022-02-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;
