SELECT
    MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
  AND DATE_OF_BIRTH IS NOT NULL
  -- 생일이 null이 섞여있을 경우 안전하게 보완하기
  AND MONTH(DATE_OF_BIRTH) = 3
  AND TLNO IS NOT NULL
  AND TLNO <> ''
ORDER BY MEMBER_ID ASC;
