SELECT
  m.MEMBER_NAME,
  r.REVIEW_TEXT,
  DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE m
  ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID = (
  SELECT rr.MEMBER_ID
  FROM REST_REVIEW rr
  GROUP BY rr.MEMBER_ID
  ORDER BY COUNT(*) DESC, rr.MEMBER_ID ASC
  LIMIT 1
)
ORDER BY
  r.REVIEW_DATE ASC,
  r.REVIEW_TEXT ASC;
