-- 2026.02.13 다음주 컴퓨터 수리예정입니닷 ㅠㅠ
WITH C AS (
  SELECT
    SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FE,
    SUM(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END)       AS PY,
    SUM(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END)           AS CS
  FROM SKILLCODES
)
SELECT
  CASE
    WHEN (D.SKILL_CODE & C.FE) > 0 AND (D.SKILL_CODE & C.PY) > 0 THEN 'A'
    WHEN (D.SKILL_CODE & C.CS) > 0 THEN 'B'
    WHEN (D.SKILL_CODE & C.FE) > 0 THEN 'C'
  END AS GRADE,
  D.ID,
  D.EMAIL
FROM DEVELOPERS D
CROSS JOIN C
WHERE
  ((D.SKILL_CODE & C.FE) > 0 AND (D.SKILL_CODE & C.PY) > 0)
  OR ((D.SKILL_CODE & C.CS) > 0)
  OR ((D.SKILL_CODE & C.FE) > 0)
ORDER BY
  GRADE ASC,
  D.ID ASC;
