-- 난이도가 조금씩 상승하네요 ㅠㅠ,,, 겨우 통과

SELECT
  c.CAR_ID,
  c.CAR_TYPE,
  FLOOR(c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
  ON p.CAR_TYPE = c.CAR_TYPE
 AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND c.CAR_ID NOT IN (
    SELECT h.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    WHERE h.START_DATE <= '2022-11-30'
      AND h.END_DATE   >= '2022-11-01'
  )
  AND (c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) >= 500000
  AND (c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) < 2000000
ORDER BY
  FEE DESC,
  c.CAR_TYPE ASC,
  c.CAR_ID DESC;
